secrets:
  certificates:
    file: ../certs/
  certificate-passwords:
    file: ./certificate-passwords/

services:
  nginx:
    image: nginx:mainline-alpine-slim
    ports:
    - 127.0.0.1:443:443
    secrets:
    - source: certificates
      target: /etc/nginx/certs
    - source: certificate-passwords
      target: /etc/nginx/secrets
    volumes:
    - ./conf.d:/etc/nginx/conf.d
